### ISSUE TITLE
Example that includes a module from npm

### ISSUE THREAD

**Issue by JuanAntelo** [netlify/netlify-functions-example#3]
Should be included

**Comment by imorente** [comment]
@JuanAntelo – we have the "fetch" example that uses an npm module https://github.com/netlify/netlify-functions-example/blob/master/src/lambda/hello_fetch.js#L1 
https://github.com/netlify/netlify-functions-example/blob/master/package.json#L26

Please feel free to open a PR to help make that clearer, or suggest an npm module you'd like to showcase. All the examples build up to the final "Send a message to Slack", so ideally it'd be along those lines.

Thanks!
